### ISSUE TITLE
datepicker clean up strategie. 

### ISSUE THREAD

**Issue by stachrom** [acidsound/bootstrap-datepicker#1]
Hi LEE 
Can you show some best practice to keep datepicker with Meteor clean?

where and how to clean up. 
- remove datepicker html
- cleanup the events & data bound

-> $('#datepicker').datepicker('remove');

Roman

**Comment by acidsound** [comment]
Maybe this link can help you. https://github.com/eternicode/bootstrap-datepicker.

I tried 'remove', but didn't works.
https://github.com/eternicode/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js#L236

It looks like the unresolved issues.
https://github.com/eternicode/bootstrap-datepicker/issues/327

**Comment by acidsound** [comment]
https://github.com/eternicode/bootstrap-datepicker/issues/327
eternicode fixed this issue. :)
